glitter/config/routes.rb
Rails.application.routes.draw do


	root to: 'users#index'
	get "/login", to: 'sessions#new'
	post "/login", to: 'sessions#create'
	get "/logout", to: 'sessions#destroy'
	get "/timeline", to: 'users#timeline'
	get "/mentions", to: 'users#mentions'

  resources :hashtags, only:[:show]

  resources :users, only: [:new, :create] do 
  	member do 
  		post 'follow'
  		post 'unfollow'
  	end
  end
  resources :statuses, only: [:new, :create, :index, :show] do
    member do
      post 'retweet'
    end
  end




  get "/:username", to: 'users#show', as: 'user'

end

glitter/app/models/mention.rb
class Mention < ActiveRecord::Base
	belongs_to :user
	belongs_to :status


	def mark_viewed!
		self.update(viewed_at: Time.now)
	end
end

glitter/app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
	belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'

end

glitter/app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
	belongs_to :parent_status, class_name: 'Status', foreign_key: 'retweet_id'

	validates :creator, presence: true
	validates :body, presence: true, length: {minimum: 5}
	after_save :extract_mentions


	def extract_mentions
		mentions = self.body.scan(/@(\w*)/)
		if mentions.size > 0
			mentions.each do |mention|
				m = mention.first
				user = User.find_by username: m
				if user
					Mention.create(user_id: user.id, status_id: self.id)
				end
			end
		end
	end
end

glitter/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :statuses
	has_many :mentions
	#has_many :unread_mentions, -> (){where('viewed_at is NULL')}, class_name: 'Mention', foreign_key: 'user_id'

	#must specify associations within the join model b/c you're working on both side of the model(User)
	has_many :follower_relationships, class_name: "Relationship", foreign_key: "leader_id"
	has_many :leader_relationships, class_name: "Relationship", foreign_key: "follower_id"
	#users that are following me
	has_many :follower_users, through: :follower_relationships, source: :follower
	#users that I follow
	has_many :following_users, through: :leader_relationships, source: :leader

	validates :username, presence: true
	validates :email, presence: true

	def num_unread_mentions
		mentions.where(viewed_at: nil).count
	end

	def unread_mentions
		mentions.where(viewed_at: nil)
	end

	def mark_unread_mentions!
		unread_mentions.each do |mention|
			mention.mark_viewed!
		end
	end



end

glitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
  def wrong_path
    flash[:notice] = "This is embarassing...something went wrong! Please try again." 
  end

end

glitter/app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController


	def show
		@statuses = Status.where("body LIKE ?", "%##{params[:id]}%")
	end

end

glitter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by username: params[:username]
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			flash[:notice] = "You're logged in!"
			redirect_to statuses_path

		else
			flash.now[:error] = "There is something wrong with your username or password."
			render :new
		end
	end


	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've logged out."
		redirect_to login_path
	end
end

glitter/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	before_action :require_user, only: [:new, :create, :retweet]

	def new
		@status = Status.new
	end


	def create
		@status = Status.new(status_params)
		#user = User.find 1 #TODO Add Authentication
		@status.creator = current_user #TODO Add Authentication

		if @status.save
			flash[:notice] = "Status created!"
			redirect_to user_path(@status.creator.username)
		else
			render :new
		end
	end

	def index
		@statuses = Status.all
	end

	def show
		@status = Status.find(params[:id])
	end
	

	def retweet
		status = Status.find(params[:id])
		new_status = Status.new(body: status.body, creator: current_user, parent_status: status)

		if new_status.save
			flash[:notice] = "Retweeted!"
		else
			flash[:error] = "Couldn't retweet!"
		end
		redirect_to :back
	end

private

	def status_params
		params.require(:status).permit(:body)
	end
end

glitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:follow, :unfollow, :mentions]

	def index
		@users = User.all

	end


	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params).downcase

		if @user.save
			flash[:notice] = "You're now registered!"
			redirect_to user_path(@user.username)
		else
			render :new
		end
	end

	def show
		@user = User.find_by username: params[:username]
		wrong_path unless @user
	end

	def follow
		user = User.find(params[:id])
		if user
			current_user.following_users << user
			flash[:notice] = "You are now following #{user.username}."
			redirect_to user_path(user.username)
		else
			wrong_path
		end
	end

	def unfollow
		user = User.find(params[:id])
		rel = Relationship.where(follower: current_user, leader: user).first
		if user && rel
			rel.destroy
			flash[:notice] = "You are no longer following #{user.username}."
			redirect_to user_path(user.username)
		else
			wrong_path
		end
	end

	def timeline
		@statuses = []
		current_user.following_users.each do |user|
			@statuses << user.statuses.all
		end
		@statuses.flatten!
	end

	def mentions
		current_user.mark_unread_mentions!
	end


	private

	def user_params
		params.require(:user).permit!
	end

end

glitter/app/helpers/application_helper.rb
module ApplicationHelper

	def auto_links(str)
		str = link_hashtag(str)
		str = link_mentions(str)
		str.html_safe
	end


	def link_hashtag(str)
		str.gsub(/#(\w+)/, "<a href='/hashtags/\\1'>#\\1</a>")
	end

	def link_mentions(str)
		str.gsub(/@(\w+)/, "<a href='/\\1'>@\\1</a>")
	end
end

glitter/app/views/hashtags/show.html.erb
<%= render 'shared/header', header: "Statuses for hashtag ##{params[:id]}" %>

<ul>
	<% @statuses.each do |status| %>
	<li><%= render 'statuses/status', status: status %></li>
	<% end %>
</ul>

glitter/app/views/layouts/_flash_messages.html.erb
<div>
<% if flash.keys.any? %>
 	<% flash.keys.each do |key| %>
 		<div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>" role="alert">
 			<%= flash[key] %>
 		</div>
 	<% end %>	
<% end %>
</div>

glitter/app/views/layouts/_top_nav.html.erb
<%= link_to "Home", root_path %> |

<% if logged_in? %>
	Welcome, <%= current_user.username.capitalize %>! |
	<%= link_to "Mentions (#{current_user.num_unread_mentions})", mentions_path %> |
	<%= link_to 'Timeline', timeline_path %> |
	<%=link_to "New Status", new_status_path %> |
	<%= link_to "Log out", logout_path %>
<% else %>

	<%=link_to "Register", new_user_path %> |

	<%=link_to "Login", login_path %> 

<% end %>

glitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render '/layouts/top_nav' %>
<%= render '/layouts/flash_messages'%>

<%= yield %>

</body>
</html>

glitter/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<h5> There were some errors: </h5>
		<ul>
		<% obj.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
		</ul>
	</div>
<% end %>

glitter/app/views/shared/_header.html.erb
<h3><%= header %></h3>

<hr/>

glitter/app/views/statuses/_status.html.erb
<%= auto_links(status.body) %> <%= link_to '*', status_path(status.parent_status) if status.retweet_id %>

<% if status.retweet_id %> 
	retweeted by 
<% else %>
	created by 
<% end %>
<%= link_to status.creator.username, user_path(status.creator.username) %>

<% if logged_in? && status.creator != current_user %>
	[<%= link_to 'retweet', retweet_status_path(status), method: 'post' %>]

<% end %>

glitter/app/views/statuses/index.html.erb
<%= render 'shared/header', header: "Recent Statuses" %>

<ul>
	<% @statuses.each do |status| %>
		<li><%= render 'statuses/status', status: status %></li>
	<% end %>
</ul>

glitter/app/views/statuses/new.html.erb
<%= render 'shared/header', header: "Create a new status" %>
<%= render 'shared/errors', obj: @status %>

<% if logged_in? %>
	<%= form_for @status do |f| %>
		<%= f.label :body %>
		<%= f.text_area :body %>
	<br/>
	<%= f.submit "Create Status", class: 'btn btn-primary' %>
	<% end %>
<% end %>

glitter/app/views/statuses/show.html.erb
<%= render 'status', status: status %>

glitter/app/views/users/index.html.erb
<%= render 'shared/header', header: "Welcome To Glitter" %>

<ul>
	<% @users.each do |user| %>
		<li><%= link_to user.username, user_path(user.username) %></li>
	<% end %>
</ul>

glitter/app/views/users/mentions.html.erb
<%= render 'shared/header', header: "Mentions" %>

<ul>
<% current_user.mentions.each do |mention| %>
	<li><%= render 'statuses/status', status: mention.status %></li>
<% end %>
</ul>

glitter/app/views/users/new.html.erb
<%= render 'shared/header', header: "Register" %>
<%= render 'shared/errors', obj: @user %>


<%= form_for @user, html: {class: 'form-horizontal', role: 'form'} do |f| %>
	<div class='form-group'>
		<%= f.label :username, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
			<%= f.text_field :username, class: "form-control" %>
		</div>
	</div>
<div class='form-group'>
	<%= f.label :email, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
	<%= f.text_field :email, class: "form-control" %>
	</div>
</div>
<div class="form-group">
	<%= f.label :password, class: "col-sm-2 control-label" %>
		<div class="col-sm-6">
			<%= f.password_field :password, class: "form-control" %>
		</div>
	</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<%= f.submit "Register", class: "btn btn-default" %>
	</div>
</div>

<% end %>

glitter/app/views/users/show.html.erb
<h3><%= link_to "@#{@user.username}", user_path(@user.username) %></h3>
<% if logged_in? %>
	<% if !current_user.following_users.include?(@user) %>
		<%= link_to "+ follow #{@user.username}", follow_user_path(@user), method: 'post' %>
	<% else %>
	<%= link_to "- unfollow #{@user.username}", unfollow_user_path(@user), method: 'post' %>
	<% end %>
<% end %>

<p>
	<ul>
	<% @user.statuses.each do |status| %>
		<li><%= render 'statuses/status', status: status %></li>
	<% end %>
</ul>
</p>

glitter/app/views/users/timeline.html.erb
<%= render 'shared/header', header: "Timeline" %>

<ul>
<% @statuses.each do |status| %>
	<li><%= status.body %> by <%= status.creator.username %> at <%= status.created_at %></li>
<% end %>
</ul>